//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunsetHackathon {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SunsetHackathon.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string day_one {
            get {
                return ResourceManager.GetString("day_one", resourceCulture);
            }
        }
        
        public static string day_two {
            get {
                return ResourceManager.GetString("day_two", resourceCulture);
            }
        }
        
        public static string day_three {
            get {
                return ResourceManager.GetString("day_three", resourceCulture);
            }
        }
        
        public static string talk_with_us {
            get {
                return ResourceManager.GetString("talk_with_us", resourceCulture);
            }
        }
        
        public static string video_stream {
            get {
                return ResourceManager.GetString("video_stream", resourceCulture);
            }
        }
        
        public static string url_day_one {
            get {
                return ResourceManager.GetString("url_day_one", resourceCulture);
            }
        }
        
        public static string url_day_two {
            get {
                return ResourceManager.GetString("url_day_two", resourceCulture);
            }
        }
        
        public static string url_day_three {
            get {
                return ResourceManager.GetString("url_day_three", resourceCulture);
            }
        }
        
        public static string url_talk_with_us {
            get {
                return ResourceManager.GetString("url_talk_with_us", resourceCulture);
            }
        }
        
        public static string url_video_stream {
            get {
                return ResourceManager.GetString("url_video_stream", resourceCulture);
            }
        }
    }
}
